mode: "osm"

grid:
  width: 40
  height: 30
  cell_size: 20

map:
  place_name: "Bamberg, Germany"
  network_type: "walk"
  simplify: true

colors:
  start: [0, 255, 0]
  goal: [255, 0, 0]
  path: [0, 0, 255]
  obstacle: [80, 80, 80]
  background: [255, 255, 255]

# OSM visualization colors
map_colors:
  node: [200, 200, 200]
  edge: [100, 100, 100]
  obstacle_edge: [200, 50, 50]

algorithm:
  type: "dstar_lite"
  diagonal_movement: false

visualization:
  tool: "pygame"
  refresh_rate: 60
  show_grid: true     # used only in GRID mode
  window_width: 1000  # used only in OSM mode
  window_height: 800

interaction:
  draw_mode: "rectangle"  # used only in GRID mode
  clear_key: "c"

logging:
  enable: true
  save_path: "logs/run.log"
